#!/usr/bin/env ruby

# All of this is from:
# http://tammersaleh.com/posts/the-modern-vim-config-with-pathogen

git_bundles = [  
  "git://github.com/scrooloose/nerdtree.git",
  "git://github.com/tpope/vim-fugitive.git",
  "git://github.com/tpope/vim-git.git",
  "git://github.com/tpope/vim-surround.git",
  "git://github.com/tpope/vim-repeat.git",
  "git://github.com/fs111/pydoc.vim.git",
  "git://github.com/mattn/calendar-vim.git",
#  "git://github.com/vim-scripts/AutomaticTexPlugin.git",
  "git://github.com/olivierverdier/vim-latex-box.git",
#  "git://github.com/jcf/vim-latex.git",
#  "git://github.com/hsitz/VimOrganizer.git",
  "git://github.com/grncdr/VimOrganizer.git",
#  "git://github.com/jceb/vim-orgmode.git",
  "git://github.com/vim-scripts/utl.vim.git",
  "git://github.com/chrisbra/NrrwRgn.git",
  "git://github.com/altercation/vim-colors-solarized.git",
]

vim_org_scripts = [
  ["IndexedSearch", "7062",  "plugin"],
]

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.cd(bundles_dir)

puts "Trashing everything (lookout!)"
Dir["*"].each {|d| FileUtils.rm_rf d }

git_bundles.each do |url|
  dir = url.split('/').last.sub(/\.git$/, '')
  puts "  Unpacking #{url} into #{dir}"
  `git clone #{url} #{dir}`
  FileUtils.rm_rf(File.join(dir, ".git"))
end

vim_org_scripts.each do |name, script_id, script_type|
  puts "  Downloading #{name}"
  local_file = File.join(name, script_type, "#{name}.vim")
  FileUtils.mkdir_p(File.dirname(local_file))
  File.open(local_file, "w") do |file|
    file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
  end
end

